### ISSUE TITLE
Inactivating only possible in compact state

### ISSUE THREAD

**Issue by mrx23dot** [ietxaniz/vscode-fold-ninja#4]
when cycling through folding state in status bar, I cannot deactivate it in expanded state

![image](https://github.com/ietxaniz/vscode-fold-ninja/assets/4163396/6dbe872d-5056-4075-8e62-4164b54fecaf)
![image](https://github.com/ietxaniz/vscode-fold-ninja/assets/4163396/c100d2fe-04fa-40f3-bf65-d94cda3f4ca9)
![image](https://github.com/ietxaniz/vscode-fold-ninja/assets/4163396/98ab95f5-a64c-449a-a08a-ef548be12317)

last one before inactive is folded, so source code stays folded, eventhough it says inactive.

I inactivate it because I don't want to see folding, so my suggestion is expand when inactive

**Comment by ietxaniz** [comment]
Thank you for your feedback. I understand that not being able to directly switch from an expanded state to inactive was an inconvenience. In response to this, I've made some updates to the Fold Ninja extension.

Now, when you click on the Fold Ninja toolbar icon, a menu will appear, offering several options including the ability to change directly from an expanded status to inactive. This should provide a more flexible and user-friendly experience.

Please try out the new version and let me know if it resolves your issue. Your feedback is valuable, and I'm happy to make further adjustments if needed. If everything is in order, please let me know so we can close this issue.
