### ISSUE TITLE
Jumps to cursor

### ISSUE THREAD

**Issue by mrx23dot** [ietxaniz/vscode-fold-ninja#5]
Type: <b>Bug</b>

1. I set my cursor to the middle of a file
2. scroll to the bottom of the file (but not click)
3. move to 2nd tab
4. move back to 1st tab
5. now it jumps to the cursor (middle), not to last position (bottom)

please prevent   jumping to cursor on tab change

disabling the addon solves the issue.

Extension version: 0.1.9
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 6.1.7601
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (3.46GB free)|
|Process Argv|--crash-reporter-id 966db8a9-ad88-4583-af2d-7906a59aa957|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ietxaniz** [comment]
Thank you for bringing this to my attention. I understand the inconvenience caused by the editor jumping to the cursor position instead of staying at the last viewed area when switching between tabs. This behavior is actually tied to the `unfoldAll` and `foldAllBlockComments` commands provided by Visual Studio Code, which the Fold Ninja extension uses.

While I am unable to directly alter the inherent behavior of these VSCode commands within the extension, I welcome any suggestions or known workarounds from the community. If you or anyone else has ideas on how to address this, please feel free to share them here. Should a viable solution arise, I would be more than willing to consider integrating it into a future update of the Fold Ninja extension.

I appreciate your understanding and am grateful for your contribution to improving Fold Ninja. Let's keep this conversation open for potential solutions that may benefit everyone using the extension.

**Comment by ietxaniz** [comment]
Hi @mrx23dot,

Thanks for your valuable suggestion regarding the handling of folding actions. I'm pleased to inform you that in the latest update (version 0.2.1) of the Fold Ninja extension, I've implemented a hash-based change detection system. This update ensures that folding actions are only triggered when there are actual changes in the file content. 

This means that if you switch tabs without modifying the file, Fold Ninja will not perform any unnecessary folding or unfolding, thereby maintaining your scroll position as it was. This should resolve the issue of the editor jumping to the cursor position on tab changes.

I've tested this solution, and it appears to resolve the issue you reported. I'd appreciate it if you could update your extension to version 0.2.1 and confirm whether it solves the problem on your end.

Looking forward to your feedback, and thanks again for your contribution to improving Fold Ninja!

Best regards,

**Comment by ietxaniz** [comment]
If we had solely relied on VS Code's built-in file change listening mechanism, it would indeed trigger the file change following algorithm with every single edit made by the user, leading to frequent, albeit small, computations.

The hash-based approach that Fold Ninja uses is tailored to minimize unnecessary computations and ensure the extension acts only when necessary — specifically, when the user switches between files. This method is critical for maintaining a non-intrusive and efficient user experience during active development sessions. It avoids the extension reacting to every minor edit.

So both methods have its advantages and its drawbacks. And it is not so evident which of the methods is more efficient, computationally.

Additionally, this approach enhances the robustness of Fold Ninja. It ensures accurate functionality even when changes are made to files outside of VS Code, such as through external tools, scripts, or other editors. When such external modifications occur, the hash will change, alerting Fold Ninja to re-evaluate the folding state once the file is reopened or refocused in VS Code. This makes the extension more reliable, as it accurately reflects the current state of the file, irrespective of how or where it was modified.

The decision to use a hash-based system over the built-in file change listeners strikes a balance between robustness and performance. While adding a step in the process, it's a small price for ensuring that Fold Ninja only acts when truly needed, thus maintaining a smoother workflow.
